//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#pragma once

namespace service
{
namespace data
{

class Container;

class Container : public virtual RobotRaconteur::RRObject
{
public:
virtual RR_SHARED_PTR<RobotRaconteur::RRArray<double > > get_data()=0;
virtual void set_data(RR_SHARED_PTR<RobotRaconteur::RRArray<double > > value)=0;

virtual std::string RRType() {return "service.data.Container";  }
};

}
}

